### ISSUE TITLE
fix: Unexpected end of input error when running fluttium test

### ISSUE THREAD

**Issue by gilescm** [wolfenrain/fluttium#29]
**Description**

An error is thrown when trying to run `fluttium test`, see the stack trace below. It seems to be an error during the intial pre test "Installing dependencies" phase.

Downloaded using `flutter pub global activate fluttium_cli` current version is `0.1.0-dev.5`

Flutter version is `3.3.4` and the target device is iOS.

```
giles@macbook mobile % fluttium test my_flow.yaml
✓ Retrieving devices (4.9s)
⠦ Installing dependencies... (1.3s)Unexpected end of input
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36:10)
#3      JsonDecoder.convert (dart:convert/json.dart:612:36)
#4      JsonCodec.decode (dart:convert/json.dart:216:41)
#5      jsonDecode (dart:convert/json.dart:155:10)
#6      FluttiumRunner._setupProject (package:fluttium_runner/src/fluttium_runner.dart:134:25)
<asynchronous suspension>
#7      FluttiumRunner.run (package:fluttium_runner/src/fluttium_runner.dart:202:5)
<asynchronous suspension>
#8      TestCommand.run (package:fluttium_cli/src/commands/test_command.dart:246:5)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     FluttiumCommandRunner.runCommand (package:fluttium_cli/src/command_runner.dart:108:18)
<asynchronous suspension>
#11     FluttiumCommandRunner.run (package:fluttium_cli/src/command_runner.dart:60:14)
<asynchronous suspension>
#12     main (file:///Users/giles/.pub-cache/hosted/pub.dartlang.org/fluttium_cli-0.1.0-dev.5/bin/fluttium.dart:6:24)
<asynchronous suspension>


Fluttium, a user flow testing tool for Flutter.

Usage: fluttium <command> [arguments]

Global options:
-h, --help            Print this usage information.
-v, --version         Print the current version.
    --[no-]verbose    Noisy logging, including all shell commands executed.

Available commands:
  create   Create a FluttiumFlow test.
  test     Run a FluttiumFlow test.
  update   Update the CLI.

Run "fluttium help <command>" for more information about a command.
```

**Steps To Reproduce**

1. Create the following `my_flow.yaml` file
```yaml
description: Login
---
- tapOn: "email"
```
3. Run fluttium test my_flow.yaml
5. See error

**Expected Behavior**

The test runs as expected.

**Additional context**

Flutter doctor --verbose

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-x64, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/giles/fvm/versions/2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (9 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/giles/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 6A00D6B8-A02C-4FAB-B8BA-E5021707C1B0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by wolfenrain** [comment]
Thank you for the bug report, could u run `flutter devices --machine` for me? Curious what output it gives

We are parsing its output as JSON, from the looks of it the stdout has some malformed data. We should at least add a try catch around it and provide proper error logging in case it fails

**Comment by gilescm** [comment]
Sure! Please see below:

```
giles@gohenry-0276 mobile % flutter devices --machine
[
  {
    "name": "iPhone 14 Pro",
    "id": "6A00D6B8-A02C-4FAB-B8BA-E5021707C1B0",
    "isSupported": true,
    "targetPlatform": "ios",
    "emulator": true,
    "sdk": "com.apple.CoreSimulator.SimRuntime.iOS-16-0",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": true,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "macOS",
    "id": "macos",
    "isSupported": true,
    "targetPlatform": "darwin",
    "emulator": false,
    "sdk": "macOS 12.5.1 21G83 darwin-x64",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": true,
      "hardwareRendering": false,
      "startPaused": true
    }
  },
  {
    "name": "Chrome",
    "id": "chrome",
    "isSupported": true,
    "targetPlatform": "web-javascript",
    "emulator": false,
    "sdk": "Google Chrome 106.0.5249.119",
    "capabilities": {
      "hotReload": true,
      "hotRestart": true,
      "screenshot": false,
      "fastStart": false,
      "flutterExit": false,
      "hardwareRendering": false,
      "startPaused": true
    }
  }
]
```

**Comment by gilescm** [comment]
Actually looking at the code I think the json it's failing to pass is the `dependencyData` output from Line 134 of (flutter_runner.dart)[https://github.com/wolfenrain/fluttium/blob/main/packages/fluttium_runner/lib/src/fluttium_runner.dart]

final projectData = jsonDecode(dependencyData.stdout as String) as Map;

That output is far too large to post here but I've just tried the standard `flutter run` and that's failed so I think it may be due to dependency issues I've got on my own machine. I'll investigate more over the weekend and let you know!

**Comment by bartekpacia** [comment]
Sometimes some stray messages may mess up JSON parsing, e.g Flutter update prompt.

**Comment by wolfenrain** [comment]
Yea was thinking the same, even tho that shouldn't be allowed with `--machine` flags, but we can add some validation checks to find correct JSON etc

**Comment by gilescm** [comment]
Resolved 🎉 and looks to be it was due to a stray message as suggested by @bartekpacia. I resolved my build issues, then ran `flutter pub deps` and received this stray message:

```
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.
```

Once I ran `flutter pub get` to sync up the `pubspec.lock` file I was able to run `flutter test test.yaml` successfully 🎉. I was thinking I could close this issue now, but should it be left open to cover adding some validation checks against messages like the above and the Flutter update prompt?

**Comment by wolfenrain** [comment]
Glad to hear it is resolved, and indeed I'll use this issue to track better handling of malformed stdouts.
